name: smart_on_fhir
description: A new Flutter package project.
version: 0.0.1
author:
homepage: https://github.com/fhir-fli/smart_on_fhir

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  freezed_annotation: ^0.12.0
  dartz: ^0.9.1
  http: ^0.12.2
  flutter_appauth: ^0.9.2+6
  # fhir: ^0.0.9
  fhir: 
    git:
      url: https://github.com/FireJuun/fhir.git
      ref: enable_when_operators 
  flutter_secure_storage: ^3.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.4.1
  freezed: ^0.12.1
  build_runner: ^1.10.1
  lint: ^1.2.0
  test: ^1.15.4

flutter:

                    
                                      